/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_java02014_genius_app_BlurNative */

#ifndef _Included_com_java02014_genius_app_BlurNative
#define _Included_com_java02014_genius_app_BlurNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_java02014_genius_app_BlurNative
 * Method:    blurPixels
 * Signature: ([IIII)V
 */JNIEXPORT void JNICALL Java_com_java02014_genius_app_BlurNative_blurPixels(
		JNIEnv *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     com_java02014_genius_app_BlurNative
 * Method:    blurBitmap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */JNIEXPORT void JNICALL Java_com_java02014_genius_app_BlurNative_blurBitmap(
		JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
